common: &common
  standalone: true
  loglevel: info
  search_backend: sqlalchemy
  sqlalchemy_index_database: sqlite:////tmp/docker-registry.db

  cache:
    host: localhost
    port: 6379
    db: 6

  cache_lru:
    host: localhost
    port: 6379
    db: 7


prod: &local
  <<: *common
  storage: file
  storate_path: /tmp/storage/registry
