default: &default
  url: http://localhost:9200
  log: true

production:
  <<: *default
  log: false
  index: itpkg

development:
  <<: *default
  index: itpkg_development

test:
  <<: *default
  index: itpkg_test

