#!/bin/sh
source $HOME/local/python2/bin/activate

DOCKER_REGISTRY_CONFIG=/etc/docker-registry.yml
SETTINGS_FLAVOR=local
STORAGE_PATH=$HOME/registry
CACHE_REDIS_HOST=localhost
CACHE_REDIS_PORT=6379
CACHE_REDIS_DB=7
CACHE_LRU_REDIS_HOST=localhost
CACHE_LRU_REDIS_PORT=6379
CACHE_LRU_REDIS_DB=7

export DOCKER_REGISTRY_CONFIG SETTINGS_FLAVOR STORAGE_PATH CACHE_REDIS_HOST CACHE_REDIS_PORT CACHE_REDIS_DB CACHE_LRU_REDIS_HOST CACHE_LRU_REDIS_PORT CACHE_LRU_REDIS_DB

docker-registry
