// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools/rpc.proto

package com.odong.itpkg.model;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code itpkg.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BYE = 0;</code>
     */
    BYE(0, 0),
    /**
     * <code>COMMAND = 1;</code>
     */
    COMMAND(1, 1),
    /**
     * <code>FILE = 2;</code>
     */
    FILE(2, 2),
    /**
     * <code>HEART = 3;</code>
     */
    HEART(3, 3),
    ;

    /**
     * <code>BYE = 0;</code>
     */
    public static final int BYE_VALUE = 0;
    /**
     * <code>COMMAND = 1;</code>
     */
    public static final int COMMAND_VALUE = 1;
    /**
     * <code>FILE = 2;</code>
     */
    public static final int FILE_VALUE = 2;
    /**
     * <code>HEART = 3;</code>
     */
    public static final int HEART_VALUE = 3;


    public final int getNumber() { return value; }

    public static Type valueOf(int value) {
      switch (value) {
        case 0: return BYE;
        case 1: return COMMAND;
        case 2: return FILE;
        case 3: return HEART;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.odong.itpkg.model.Rpc.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:itpkg.Type)
  }

  /**
   * Protobuf enum {@code itpkg.Code}
   */
  public enum Code
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(0, 1),
    /**
     * <code>FAIL = -1;</code>
     */
    FAIL(1, -1),
    ;

    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>FAIL = -1;</code>
     */
    public static final int FAIL_VALUE = -1;


    public final int getNumber() { return value; }

    public static Code valueOf(int value) {
      switch (value) {
        case 1: return SUCCESS;
        case -1: return FAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Code>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Code>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Code>() {
            public Code findValueByNumber(int number) {
              return Code.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.odong.itpkg.model.Rpc.getDescriptor().getEnumTypes().get(1);
    }

    private static final Code[] VALUES = values();

    public static Code valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Code(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:itpkg.Code)
  }

  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .itpkg.Type type = 1;
    /**
     * <code>required .itpkg.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .itpkg.Type type = 1;</code>
     */
    com.odong.itpkg.model.Rpc.Type getType();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string mode = 3;
    /**
     * <code>optional string mode = 3;</code>
     */
    boolean hasMode();
    /**
     * <code>optional string mode = 3;</code>
     */
    java.lang.String getMode();
    /**
     * <code>optional string mode = 3;</code>
     */
    com.google.protobuf.ByteString
        getModeBytes();

    // repeated string lines = 4;
    /**
     * <code>repeated string lines = 4;</code>
     */
    java.util.List<java.lang.String>
    getLinesList();
    /**
     * <code>repeated string lines = 4;</code>
     */
    int getLinesCount();
    /**
     * <code>repeated string lines = 4;</code>
     */
    java.lang.String getLines(int index);
    /**
     * <code>repeated string lines = 4;</code>
     */
    com.google.protobuf.ByteString
        getLinesBytes(int index);

    // required int64 created = 5;
    /**
     * <code>required int64 created = 5;</code>
     */
    boolean hasCreated();
    /**
     * <code>required int64 created = 5;</code>
     */
    long getCreated();

    // required string sign = 6;
    /**
     * <code>required string sign = 6;</code>
     */
    boolean hasSign();
    /**
     * <code>required string sign = 6;</code>
     */
    java.lang.String getSign();
    /**
     * <code>required string sign = 6;</code>
     */
    com.google.protobuf.ByteString
        getSignBytes();
  }
  /**
   * Protobuf type {@code itpkg.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.odong.itpkg.model.Rpc.Type value = com.odong.itpkg.model.Rpc.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              mode_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                lines_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              lines_.add(input.readBytes());
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              created_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              sign_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          lines_ = new com.google.protobuf.UnmodifiableLazyStringList(lines_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.odong.itpkg.model.Rpc.internal_static_itpkg_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.odong.itpkg.model.Rpc.internal_static_itpkg_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.odong.itpkg.model.Rpc.Request.class, com.odong.itpkg.model.Rpc.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .itpkg.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.odong.itpkg.model.Rpc.Type type_;
    /**
     * <code>required .itpkg.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .itpkg.Type type = 1;</code>
     */
    public com.odong.itpkg.model.Rpc.Type getType() {
      return type_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string mode = 3;
    public static final int MODE_FIELD_NUMBER = 3;
    private java.lang.Object mode_;
    /**
     * <code>optional string mode = 3;</code>
     */
    public boolean hasMode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string mode = 3;</code>
     */
    public java.lang.String getMode() {
      java.lang.Object ref = mode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getModeBytes() {
      java.lang.Object ref = mode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string lines = 4;
    public static final int LINES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList lines_;
    /**
     * <code>repeated string lines = 4;</code>
     */
    public java.util.List<java.lang.String>
        getLinesList() {
      return lines_;
    }
    /**
     * <code>repeated string lines = 4;</code>
     */
    public int getLinesCount() {
      return lines_.size();
    }
    /**
     * <code>repeated string lines = 4;</code>
     */
    public java.lang.String getLines(int index) {
      return lines_.get(index);
    }
    /**
     * <code>repeated string lines = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLinesBytes(int index) {
      return lines_.getByteString(index);
    }

    // required int64 created = 5;
    public static final int CREATED_FIELD_NUMBER = 5;
    private long created_;
    /**
     * <code>required int64 created = 5;</code>
     */
    public boolean hasCreated() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 created = 5;</code>
     */
    public long getCreated() {
      return created_;
    }

    // required string sign = 6;
    public static final int SIGN_FIELD_NUMBER = 6;
    private java.lang.Object sign_;
    /**
     * <code>required string sign = 6;</code>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string sign = 6;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sign = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = com.odong.itpkg.model.Rpc.Type.BYE;
      name_ = "";
      mode_ = "";
      lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      created_ = 0L;
      sign_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSign()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getModeBytes());
      }
      for (int i = 0; i < lines_.size(); i++) {
        output.writeBytes(4, lines_.getByteString(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(5, created_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getSignBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getModeBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < lines_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(lines_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getLinesList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, created_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSignBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.odong.itpkg.model.Rpc.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odong.itpkg.model.Rpc.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odong.itpkg.model.Rpc.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odong.itpkg.model.Rpc.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odong.itpkg.model.Rpc.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.odong.itpkg.model.Rpc.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.odong.itpkg.model.Rpc.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.odong.itpkg.model.Rpc.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.odong.itpkg.model.Rpc.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.odong.itpkg.model.Rpc.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.odong.itpkg.model.Rpc.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code itpkg.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.odong.itpkg.model.Rpc.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.odong.itpkg.model.Rpc.internal_static_itpkg_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.odong.itpkg.model.Rpc.internal_static_itpkg_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.odong.itpkg.model.Rpc.Request.class, com.odong.itpkg.model.Rpc.Request.Builder.class);
      }

      // Construct using com.odong.itpkg.model.Rpc.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.odong.itpkg.model.Rpc.Type.BYE;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        mode_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        created_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.odong.itpkg.model.Rpc.internal_static_itpkg_Request_descriptor;
      }

      public com.odong.itpkg.model.Rpc.Request getDefaultInstanceForType() {
        return com.odong.itpkg.model.Rpc.Request.getDefaultInstance();
      }

      public com.odong.itpkg.model.Rpc.Request build() {
        com.odong.itpkg.model.Rpc.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.odong.itpkg.model.Rpc.Request buildPartial() {
        com.odong.itpkg.model.Rpc.Request result = new com.odong.itpkg.model.Rpc.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mode_ = mode_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          lines_ = new com.google.protobuf.UnmodifiableLazyStringList(
              lines_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.lines_ = lines_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.created_ = created_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sign_ = sign_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.odong.itpkg.model.Rpc.Request) {
          return mergeFrom((com.odong.itpkg.model.Rpc.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.odong.itpkg.model.Rpc.Request other) {
        if (other == com.odong.itpkg.model.Rpc.Request.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMode()) {
          bitField0_ |= 0x00000004;
          mode_ = other.mode_;
          onChanged();
        }
        if (!other.lines_.isEmpty()) {
          if (lines_.isEmpty()) {
            lines_ = other.lines_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLinesIsMutable();
            lines_.addAll(other.lines_);
          }
          onChanged();
        }
        if (other.hasCreated()) {
          setCreated(other.getCreated());
        }
        if (other.hasSign()) {
          bitField0_ |= 0x00000020;
          sign_ = other.sign_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasCreated()) {
          
          return false;
        }
        if (!hasSign()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.odong.itpkg.model.Rpc.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.odong.itpkg.model.Rpc.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .itpkg.Type type = 1;
      private com.odong.itpkg.model.Rpc.Type type_ = com.odong.itpkg.model.Rpc.Type.BYE;
      /**
       * <code>required .itpkg.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .itpkg.Type type = 1;</code>
       */
      public com.odong.itpkg.model.Rpc.Type getType() {
        return type_;
      }
      /**
       * <code>required .itpkg.Type type = 1;</code>
       */
      public Builder setType(com.odong.itpkg.model.Rpc.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .itpkg.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.odong.itpkg.model.Rpc.Type.BYE;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string mode = 3;
      private java.lang.Object mode_ = "";
      /**
       * <code>optional string mode = 3;</code>
       */
      public boolean hasMode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string mode = 3;</code>
       */
      public java.lang.String getMode() {
        java.lang.Object ref = mode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getModeBytes() {
        java.lang.Object ref = mode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mode = 3;</code>
       */
      public Builder setMode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mode = 3;</code>
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mode_ = getDefaultInstance().getMode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mode = 3;</code>
       */
      public Builder setModeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mode_ = value;
        onChanged();
        return this;
      }

      // repeated string lines = 4;
      private com.google.protobuf.LazyStringList lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLinesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          lines_ = new com.google.protobuf.LazyStringArrayList(lines_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string lines = 4;</code>
       */
      public java.util.List<java.lang.String>
          getLinesList() {
        return java.util.Collections.unmodifiableList(lines_);
      }
      /**
       * <code>repeated string lines = 4;</code>
       */
      public int getLinesCount() {
        return lines_.size();
      }
      /**
       * <code>repeated string lines = 4;</code>
       */
      public java.lang.String getLines(int index) {
        return lines_.get(index);
      }
      /**
       * <code>repeated string lines = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLinesBytes(int index) {
        return lines_.getByteString(index);
      }
      /**
       * <code>repeated string lines = 4;</code>
       */
      public Builder setLines(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinesIsMutable();
        lines_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lines = 4;</code>
       */
      public Builder addLines(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinesIsMutable();
        lines_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lines = 4;</code>
       */
      public Builder addAllLines(
          java.lang.Iterable<java.lang.String> values) {
        ensureLinesIsMutable();
        super.addAll(values, lines_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lines = 4;</code>
       */
      public Builder clearLines() {
        lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lines = 4;</code>
       */
      public Builder addLinesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinesIsMutable();
        lines_.add(value);
        onChanged();
        return this;
      }

      // required int64 created = 5;
      private long created_ ;
      /**
       * <code>required int64 created = 5;</code>
       */
      public boolean hasCreated() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 created = 5;</code>
       */
      public long getCreated() {
        return created_;
      }
      /**
       * <code>required int64 created = 5;</code>
       */
      public Builder setCreated(long value) {
        bitField0_ |= 0x00000010;
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 created = 5;</code>
       */
      public Builder clearCreated() {
        bitField0_ = (bitField0_ & ~0x00000010);
        created_ = 0L;
        onChanged();
        return this;
      }

      // required string sign = 6;
      private java.lang.Object sign_ = "";
      /**
       * <code>required string sign = 6;</code>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string sign = 6;</code>
       */
      public java.lang.String getSign() {
        java.lang.Object ref = sign_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sign = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        java.lang.Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sign = 6;</code>
       */
      public Builder setSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 6;</code>
       */
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 6;</code>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sign_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:itpkg.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:itpkg.Request)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .itpkg.Type type = 1;
    /**
     * <code>required .itpkg.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .itpkg.Type type = 1;</code>
     */
    com.odong.itpkg.model.Rpc.Type getType();

    // required .itpkg.Code code = 2;
    /**
     * <code>required .itpkg.Code code = 2;</code>
     */
    boolean hasCode();
    /**
     * <code>required .itpkg.Code code = 2;</code>
     */
    com.odong.itpkg.model.Rpc.Code getCode();

    // repeated string lines = 3;
    /**
     * <code>repeated string lines = 3;</code>
     */
    java.util.List<java.lang.String>
    getLinesList();
    /**
     * <code>repeated string lines = 3;</code>
     */
    int getLinesCount();
    /**
     * <code>repeated string lines = 3;</code>
     */
    java.lang.String getLines(int index);
    /**
     * <code>repeated string lines = 3;</code>
     */
    com.google.protobuf.ByteString
        getLinesBytes(int index);

    // required int64 created = 4;
    /**
     * <code>required int64 created = 4;</code>
     */
    boolean hasCreated();
    /**
     * <code>required int64 created = 4;</code>
     */
    long getCreated();
  }
  /**
   * Protobuf type {@code itpkg.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.odong.itpkg.model.Rpc.Type value = com.odong.itpkg.model.Rpc.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.odong.itpkg.model.Rpc.Code value = com.odong.itpkg.model.Rpc.Code.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                code_ = value;
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                lines_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              lines_.add(input.readBytes());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              created_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          lines_ = new com.google.protobuf.UnmodifiableLazyStringList(lines_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.odong.itpkg.model.Rpc.internal_static_itpkg_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.odong.itpkg.model.Rpc.internal_static_itpkg_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.odong.itpkg.model.Rpc.Response.class, com.odong.itpkg.model.Rpc.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .itpkg.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.odong.itpkg.model.Rpc.Type type_;
    /**
     * <code>required .itpkg.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .itpkg.Type type = 1;</code>
     */
    public com.odong.itpkg.model.Rpc.Type getType() {
      return type_;
    }

    // required .itpkg.Code code = 2;
    public static final int CODE_FIELD_NUMBER = 2;
    private com.odong.itpkg.model.Rpc.Code code_;
    /**
     * <code>required .itpkg.Code code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .itpkg.Code code = 2;</code>
     */
    public com.odong.itpkg.model.Rpc.Code getCode() {
      return code_;
    }

    // repeated string lines = 3;
    public static final int LINES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList lines_;
    /**
     * <code>repeated string lines = 3;</code>
     */
    public java.util.List<java.lang.String>
        getLinesList() {
      return lines_;
    }
    /**
     * <code>repeated string lines = 3;</code>
     */
    public int getLinesCount() {
      return lines_.size();
    }
    /**
     * <code>repeated string lines = 3;</code>
     */
    public java.lang.String getLines(int index) {
      return lines_.get(index);
    }
    /**
     * <code>repeated string lines = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLinesBytes(int index) {
      return lines_.getByteString(index);
    }

    // required int64 created = 4;
    public static final int CREATED_FIELD_NUMBER = 4;
    private long created_;
    /**
     * <code>required int64 created = 4;</code>
     */
    public boolean hasCreated() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 created = 4;</code>
     */
    public long getCreated() {
      return created_;
    }

    private void initFields() {
      type_ = com.odong.itpkg.model.Rpc.Type.BYE;
      code_ = com.odong.itpkg.model.Rpc.Code.SUCCESS;
      lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      created_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, code_.getNumber());
      }
      for (int i = 0; i < lines_.size(); i++) {
        output.writeBytes(3, lines_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, created_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, code_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < lines_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(lines_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getLinesList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, created_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.odong.itpkg.model.Rpc.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odong.itpkg.model.Rpc.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odong.itpkg.model.Rpc.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odong.itpkg.model.Rpc.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odong.itpkg.model.Rpc.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.odong.itpkg.model.Rpc.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.odong.itpkg.model.Rpc.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.odong.itpkg.model.Rpc.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.odong.itpkg.model.Rpc.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.odong.itpkg.model.Rpc.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.odong.itpkg.model.Rpc.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code itpkg.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.odong.itpkg.model.Rpc.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.odong.itpkg.model.Rpc.internal_static_itpkg_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.odong.itpkg.model.Rpc.internal_static_itpkg_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.odong.itpkg.model.Rpc.Response.class, com.odong.itpkg.model.Rpc.Response.Builder.class);
      }

      // Construct using com.odong.itpkg.model.Rpc.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.odong.itpkg.model.Rpc.Type.BYE;
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = com.odong.itpkg.model.Rpc.Code.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        created_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.odong.itpkg.model.Rpc.internal_static_itpkg_Response_descriptor;
      }

      public com.odong.itpkg.model.Rpc.Response getDefaultInstanceForType() {
        return com.odong.itpkg.model.Rpc.Response.getDefaultInstance();
      }

      public com.odong.itpkg.model.Rpc.Response build() {
        com.odong.itpkg.model.Rpc.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.odong.itpkg.model.Rpc.Response buildPartial() {
        com.odong.itpkg.model.Rpc.Response result = new com.odong.itpkg.model.Rpc.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          lines_ = new com.google.protobuf.UnmodifiableLazyStringList(
              lines_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.lines_ = lines_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.created_ = created_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.odong.itpkg.model.Rpc.Response) {
          return mergeFrom((com.odong.itpkg.model.Rpc.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.odong.itpkg.model.Rpc.Response other) {
        if (other == com.odong.itpkg.model.Rpc.Response.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (!other.lines_.isEmpty()) {
          if (lines_.isEmpty()) {
            lines_ = other.lines_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureLinesIsMutable();
            lines_.addAll(other.lines_);
          }
          onChanged();
        }
        if (other.hasCreated()) {
          setCreated(other.getCreated());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasCode()) {
          
          return false;
        }
        if (!hasCreated()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.odong.itpkg.model.Rpc.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.odong.itpkg.model.Rpc.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .itpkg.Type type = 1;
      private com.odong.itpkg.model.Rpc.Type type_ = com.odong.itpkg.model.Rpc.Type.BYE;
      /**
       * <code>required .itpkg.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .itpkg.Type type = 1;</code>
       */
      public com.odong.itpkg.model.Rpc.Type getType() {
        return type_;
      }
      /**
       * <code>required .itpkg.Type type = 1;</code>
       */
      public Builder setType(com.odong.itpkg.model.Rpc.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .itpkg.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.odong.itpkg.model.Rpc.Type.BYE;
        onChanged();
        return this;
      }

      // required .itpkg.Code code = 2;
      private com.odong.itpkg.model.Rpc.Code code_ = com.odong.itpkg.model.Rpc.Code.SUCCESS;
      /**
       * <code>required .itpkg.Code code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .itpkg.Code code = 2;</code>
       */
      public com.odong.itpkg.model.Rpc.Code getCode() {
        return code_;
      }
      /**
       * <code>required .itpkg.Code code = 2;</code>
       */
      public Builder setCode(com.odong.itpkg.model.Rpc.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .itpkg.Code code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = com.odong.itpkg.model.Rpc.Code.SUCCESS;
        onChanged();
        return this;
      }

      // repeated string lines = 3;
      private com.google.protobuf.LazyStringList lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLinesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          lines_ = new com.google.protobuf.LazyStringArrayList(lines_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string lines = 3;</code>
       */
      public java.util.List<java.lang.String>
          getLinesList() {
        return java.util.Collections.unmodifiableList(lines_);
      }
      /**
       * <code>repeated string lines = 3;</code>
       */
      public int getLinesCount() {
        return lines_.size();
      }
      /**
       * <code>repeated string lines = 3;</code>
       */
      public java.lang.String getLines(int index) {
        return lines_.get(index);
      }
      /**
       * <code>repeated string lines = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLinesBytes(int index) {
        return lines_.getByteString(index);
      }
      /**
       * <code>repeated string lines = 3;</code>
       */
      public Builder setLines(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinesIsMutable();
        lines_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lines = 3;</code>
       */
      public Builder addLines(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinesIsMutable();
        lines_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lines = 3;</code>
       */
      public Builder addAllLines(
          java.lang.Iterable<java.lang.String> values) {
        ensureLinesIsMutable();
        super.addAll(values, lines_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lines = 3;</code>
       */
      public Builder clearLines() {
        lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string lines = 3;</code>
       */
      public Builder addLinesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinesIsMutable();
        lines_.add(value);
        onChanged();
        return this;
      }

      // required int64 created = 4;
      private long created_ ;
      /**
       * <code>required int64 created = 4;</code>
       */
      public boolean hasCreated() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 created = 4;</code>
       */
      public long getCreated() {
        return created_;
      }
      /**
       * <code>required int64 created = 4;</code>
       */
      public Builder setCreated(long value) {
        bitField0_ |= 0x00000008;
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 created = 4;</code>
       */
      public Builder clearCreated() {
        bitField0_ = (bitField0_ & ~0x00000008);
        created_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:itpkg.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:itpkg.Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_itpkg_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_itpkg_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_itpkg_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_itpkg_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017tools/rpc.proto\022\005itpkg\"n\n\007Request\022\031\n\004t" +
      "ype\030\001 \002(\0162\013.itpkg.Type\022\014\n\004name\030\002 \001(\t\022\014\n\004" +
      "mode\030\003 \001(\t\022\r\n\005lines\030\004 \003(\t\022\017\n\007created\030\005 \002" +
      "(\003\022\014\n\004sign\030\006 \002(\t\"`\n\010Response\022\031\n\004type\030\001 \002" +
      "(\0162\013.itpkg.Type\022\031\n\004code\030\002 \002(\0162\013.itpkg.Co" +
      "de\022\r\n\005lines\030\003 \003(\t\022\017\n\007created\030\004 \002(\003*1\n\004Ty" +
      "pe\022\007\n\003BYE\020\000\022\013\n\007COMMAND\020\001\022\010\n\004FILE\020\002\022\t\n\005HE" +
      "ART\020\003*&\n\004Code\022\013\n\007SUCCESS\020\001\022\021\n\004FAIL\020\377\377\377\377\377" +
      "\377\377\377\377\001B\034\n\025com.odong.itpkg.modelB\003Rpc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_itpkg_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_itpkg_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_itpkg_Request_descriptor,
              new java.lang.String[] { "Type", "Name", "Mode", "Lines", "Created", "Sign", });
          internal_static_itpkg_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_itpkg_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_itpkg_Response_descriptor,
              new java.lang.String[] { "Type", "Code", "Lines", "Created", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
