#!/bin/sh

NAME=itpkg_instance
MNT=$(pwd)/mnt

#if [ "$(id -u)" != "0" ]; then sudo='sudo' ; fi

#[ -d $MNT ] || mkdir -

if docker ps -a | grep --quiet $NAME
then
	ARGS="start $NAME"
else
	ARGS="run -p 2222:22 -p 443:443 -p 25:25 --name $NAME -P --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d itpkg:latest"
fi

case $1 in
	remove)
		docker rm $NAME
		;;
	start)
		docker $ARGS
		;;
	stop)
		docker stop $NAME
		;;
	build)
		docker build $2 -t chonglou/itpkg .
		;;
	status)
		docker version
		docker info
		docker ps
		;;
	logs)
		docker logs -f $NAME
		;;
	push)
		docker push chonglou/itpkg
		;;
	ssh)
		ssh -p 2222 root@localhost
		;;
	*)
		echo 'Usage: ./itpkg.sh start|stop|status|remove|logs'
esac

