#!/bin/sh

NAME=itpkg_running
MNT=$(pwd)/mnt

if [ "$(id -u)" != "0" ]; then sudo='sudo' ; fi

if $sudo docker ps -a | grep --quiet $NAME
then
	ARGS="start $NAME"
else
	ARGS="run -p 2222:22 --name $NAME -P --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $MNT:/mnt -d itpkg:latest"
fi

case $1 in
	setup)
		;;
	remove)
		$sudo docker rm $NAME
		;;
	start)
		if [ -d $MNT ] 
		then
			$sudo docker $ARGS
		else
			echo "Directory $MNT not exists!"
		fi
		;;
	stop)
		$sudo docker stop $NAME
		;;
	build)
		$sudo docker build $2 -t itpkg .
		;;
	status)
		$sudo docker version
		$sudo docker info
		$sudo docker ps
		;;
	logs)
		$sudo docker logs -f $NAME
		;;
	*)
		echo 'Usage: ./itpkg.sh start|stop|status|remove|logs|setup'
esac

